# Generated by Django 5.2 on 2025-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
            ],
        ),
    ]
